### ISSUE TITLE
lg2 stderr output is too verbose

### ISSUE THREAD

**Issue by jonathan-doman** [openbmc/phosphor-logging#26]
When a program is running interactively, the log messages are printed to stderr, which is a really nice valuable feature. But often the function names prefixed to each line are huge and obscure the actual content of the log message.

I would like to request that the default format in `cerr_extra_output` is changed to remove the `function_name`, or preferably, that `extra_output_method` is exposed outside the library so that the user can set their own function to do custom formatting.

**Comment by williamspatrick** [comment]
I can’t assign myself this but I think I could make some improvements here. 

What do you think about having the format be optionally read from an environment variable?

**Comment by williamspatrick** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/48825 lg2: reduce stdout and allow customization [NEW]
