### ISSUE TITLE
Rework passing the arguments to the generation script

### ISSUE THREAD

**Issue by anoo1** [openbmc/phosphor-logging#6]
Currently the YAML_DIR* variables are passed to the elog-gen.py via the configure.ac file. It would be a little cleaner to just not pass the argument to the python script in this case.  Ex in PIM Makefile.am:

 if IFACES_PATH
 PIMGEN_ARGS=-i $(IFACES_PATH)
 endif
 generated.cpp:
        $(AM_V_GEN)$(PYTHON) $(top_srcdir)/pimgen.py $(PIMGEN_ARGS) -d $(extra_yamldir)/.. -o $(builddir) generate-cpp

**Comment by williamspatrick** [comment]
Pretty sure some of this was fixed in the transition to meson.
