### ISSUE TITLE
Commits to phosphor-logger are slow

### ISSUE THREAD

**Issue by wak-google** [openbmc/phosphor-logging#9]
I've noticed a 5s+ delay for sending requests to the logger from ipmid, we need to look into ways for speeding this up because it causes unacceptable delays in the ipmi stack. Maybe prefer asynchronous requests as we don't need to block returning up the stack on error reporting.

**Comment by wak-google** [comment]
https://gerrit.openbmc-project.xyz/#/c/11150/

**Comment by dkodihal** [comment]
Issue moved to [openbmc/openbmc #3259](https://github.com/openbmc/openbmc/issues/3259) via [**ZenHub**](https://www.zenhub.com/)
